console.log("GCS_BUCKET_NAME:", process.env.GCS_BUCKET_NAME);
console.log("GOOGLE_PROJECT_ID:", process.env.GOOGLE_PROJECT_ID);
console.log("GOOGLE_CLIENT_EMAIL:", process.env.GOOGLE_CLIENT_EMAIL);
console.log("GOOGLE_APPLICATION_CREDENTIALS:", process.env.GOOGLE_APPLICATION_CREDENTIALS);
